# Generated by Django 3.0.4 on 2020-03-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='all_food_but_soups_prices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='menus',
            name='menu_items',
            field=models.CharField(default='added food or soup item here', max_length=120),
        ),
        migrations.AddField(
            model_name='menus',
            name='menu_items_description',
            field=models.TextField(default='describe food or soup item here'),
        ),
        migrations.AddField(
            model_name='menus',
            name='soup_prices',
            field=models.CharField(blank=True, choices=[('$4.00', '$4.00'), ('6.80', '$6.80'), ('$12.06', '$12.06')], default='6.80', max_length=150, null=True),
        ),
    ]
