# Generated by Django 3.0.4 on 2020-03-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20200329_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BREAKFAST MENU', 'BREAKFAST MENU'), ('LUNCH MENU', 'LUNCH MENU')], default='BREAKFAST MENU', max_length=150)),
                ('name', models.CharField(default='Add items here', max_length=120)),
                ('description', models.TextField(default='Add items here')),
                ('prices', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoupMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soup_prices', models.CharField(blank=True, choices=[('$4.00', '$4.00'), ('6.80', '$6.80'), ('$12.06', '$12.06')], default='6.80', max_length=150, null=True)),
                ('soup_name', models.CharField(default='add soup name here', max_length=120, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Menus',
        ),
    ]
