# Generated by Django 3.0.4 on 2020-03-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20200330_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='soupmenu',
            name='soup_sizes',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Select soup size', max_length=6),
        ),
    ]
