# Generated by Django 3.0.4 on 2020-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_soupmenu_soup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenus',
            name='food_thumb_img',
            field=models.ImageField(default='Upload image', upload_to=''),
        ),
    ]
