# Generated by Django 3.0.4 on 2020-04-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_soupmenu_food_thumb_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soupmenu',
            old_name='food_thumb_img',
            new_name='soup_thumb_img',
        ),
    ]
