# Generated by Django 3.0.5 on 2020-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlogfeeder', '0002_auto_20200421_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phlogfeeder',
            name='phlog_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
