# Generated by Django 3.0.5 on 2020-04-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlogfeeder', '0003_auto_20200422_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phlogfeeder',
            name='phlog_image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
