# Generated by Django 3.0.5 on 2020-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlogfeeder', '0004_auto_20200423_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phlogfeeder',
            name='phlog_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
