# Generated by Django 3.0.5 on 2020-04-30 09:03

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('phlogfeeder', '0005_auto_20200426_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phlogfeeder',
            name='phlog_image_url',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
