# Generated by Django 3.0.6 on 2020-05-07 11:22

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('phlogfeeder', '0006_auto_20200430_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phlogfeeder',
            name='phlog_image_url',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
