# Generated by Django 3.0.6 on 2020-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlogfeeder', '0007_auto_20200507_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phlogfeeder',
            name='phlog_image_url',
            field=models.CharField(max_length=200),
        ),
    ]
